In [321]:
import os
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as plt

%matplotlib inline

## Setting Paths

In [322]:
DATAPATH = "../data/"
DATAFILE_NAME = os.path.join(DATAPATH, "medical-appointments-no-show-en.csv")
ICD10FILE_NAME = os.path.join(DATAPATH, "icd10_2019.csv")

## Loading the data into a df, collecting infos and preparing terrain

In [323]:
if os.path.exists(ICD10FILE_NAME):
    icd10 = pd.read_csv(ICD10FILE_NAME)
    icd10 = icd10[
        [
            "sub-code",
            "definition",
        ]
    ]
    display(
        icd10,
    )

      sub-code                                         definition
0          A00                                            Cholera
1        A00.0  Cholera due to Vibrio cholerae 01, biovar chol...
2        A00.1    Cholera due to Vibrio cholerae 01, biovar eltor
3        A00.9                               Cholera, unspecified
4          A01                     Typhoid and paratyphoid fevers
...        ...                                                ...
11238    U84.3              Resistance to tuberculostatic drug(s)
11239    U84.7         Resistance to multiple antimicrobial drugs
11240    U84.8   Resistance to other specified antimicrobial drug
11241    U84.9      Resistance to unspecified antimicrobial drugs
11242      U85                 Resistance to antineoplastic drugs

[11243 rows x 2 columns]

In [324]:
if os.path.exists(DATAFILE_NAME):
    data = pd.read_csv(DATAFILE_NAME)
    display(data, data.info(), data.describe(), data.isna().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49593 entries, 0 to 49592
Data columns (total 26 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   specialty                42139 non-null  object
 1   appointment_time         49593 non-null  object
 2   gender                   49593 non-null  object
 3   appointment_date         49593 non-null  object
 4   no_show                  49593 non-null  object
 5   no_show_reason           1737 non-null   object
 6   disability               44456 non-null  object
 7   date_of_birth            39272 non-null  object
 8   entry_service_date       44438 non-null  object
 9   city                     44412 non-null  object
 10  icd                      10717 non-null  object
 11  appointment_month        49593 non-null  object
 12  appointment_year         49593 non-null  int64
 13  appointment_shift        49593 non-null  object
 14  age                      39243 non-null  float64
 15  under_12_years_old       49593 non-null  int64
 16  over_60_years_old        49593 non-null  int64
 17  patient_needs_companion  49593 non-null  int64
 18  average_temp_day         48577 non-null  float64
 19  average_rain_day         48577 non-null  float64
 20  max_temp_day             48577 non-null  float64
 21  max_rain_day             48577 non-null  float64
 22  rainy_day_before         49593 non-null  int64
 23  storm_day_before         49593 non-null  int64
 24  rain_intensity           49593 non-null  object
 25  heat_intensity           49593 non-null  object
dtypes: float64(5), int64(6), object(15)
memory usage: 9.8+ MB

,specialty,appointment_time,gender,appointment_date,no_show,no_show_reason,disability,date_of_birth,entry_service_date,city,...,over_60_years_old,patient_needs_companion,average_temp_day,average_rain_day,max_temp_day,max_rain_day,rainy_day_before,storm_day_before,rain_intensity,heat_intensity
0,physiotherapy,13:20,M,09/09/2021,yes,surto,NaN,NaN,NaN,NaN,...,0,0,20.75,0.01,23.7,0.2,1,1,no_rain,mild
1,psychotherapy,13:20,M,09/09/2021,no,NaN,NaN,NaN,NaN,NaN,...,0,0,20.75,0.01,23.7,0.2,1,1,no_rain,mild
2,speech therapy,13:20,F,09/09/2021,no,NaN,NaN,NaN,NaN,NaN,...,0,0,20.75,0.01,23.7,0.2,1,1,no_rain,mild
3,physiotherapy,13:20,F,09/09/2021,no,NaN,NaN,NaN,NaN,NaN,...,0,0,20.75,0.01,23.7,0.2,1,1,no_rain,mild
4,physiotherapy,14:00,M,09/09/2021,no,NaN,motor,10/10/1954,5/2/2020,B. CAMBORIU,...,1,1,20.75,0.01,23.7,0.2,1,1,no_rain,mild
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49588,NaN,10:20,M,01/02/2022,yes,pai tem médico,intellectual,9/3/2009,5/11/2019,ITAJAÍ,...,0,0,NaN,NaN,NaN,NaN,0,0,no_rain,heavy_cold
49589,NaN,10:20,M,01/02/2022,yes,NaN,NaN,NaN,NaN,NaN,...,0,0,NaN,NaN,NaN,NaN,0,0,no_rain,heavy_cold
49590,NaN,11:00,M,01/02/2022,no,NaN,intellectual,7/3/2016,11/2/2020,BOMBINHAS,...,0,1,NaN,NaN,NaN,NaN,0,0,no_rain,heavy_cold
49591,psychotherapy,11:00,M,01/02/2022,yes,NaN,NaN,NaN,NaN,NaN,...,0,0,NaN,NaN,NaN,NaN,0,0,no_rain,heavy_cold
49592,NaN,11:00,M,01/02/2022,no,NaN,intellectual,25/4/2016,2/9/2020,ITAJAÍ,...,0,1,NaN,NaN,NaN,NaN,0,0,no_rain,heavy_cold

None

,appointment_year,age,under_12_years_old,over_60_years_old,patient_needs_companion,average_temp_day,average_rain_day,max_temp_day,max_rain_day,rainy_day_before,storm_day_before
count,49593.000000,39243.000000,49593.000000,49593.000000,49593.000000,48577.000000,48577.000000,48577.000000,48577.000000,49593.000000,49593.000000
mean,2018.255076,18.522361,0.472446,0.071784,0.544230,19.748317,0.190119,23.961984,1.895687,0.981005,0.981005
std,1.736964,19.234999,0.499245,0.258133,0.498045,3.428767,0.452214,3.819804,4.445412,0.136507,0.136507
min,2016.000000,2.000000,0.000000,0.000000,0.000000,8.940000,0.000000,13.300000,0.000000,0.000000,0.000000
25%,2017.000000,8.000000,0.000000,0.000000,0.000000,17.480000,0.000000,21.400000,0.000000,1.000000,1.000000
50%,2018.000000,11.000000,0.000000,0.000000,1.000000,20.060000,0.010000,23.900000,0.200000,1.000000,1.000000
75%,2019.000000,15.000000,1.000000,0.000000,1.000000,22.120000,0.150000,26.500000,1.600000,1.000000,1.000000
max,2022.000000,110.000000,1.000000,1.000000,1.000000,28.010000,4.770000,35.400000,45.000000,1.000000,1.000000

specialty                   7454
appointment_time               0
gender                         0
appointment_date               0
no_show                        0
no_show_reason             47856
disability                  5137
date_of_birth              10321
entry_service_date          5155
city                        5181
icd                        38876
appointment_month              0
appointment_year               0
appointment_shift              0
age                        10350
under_12_years_old             0
over_60_years_old              0
patient_needs_companion        0
average_temp_day            1016
average_rain_day            1016
max_temp_day                1016
max_rain_day                1016
rainy_day_before               0
storm_day_before               0
rain_intensity                 0
heat_intensity                 0
dtype: int64

In [325]:
if not data.empty:

    data["appointment_date"] = pd.to_datetime(
        data["appointment_date"], errors="coerce", format="%d/%m/%Y"
    ).dt.strftime("%Y-%m-%d")

    data["entry_service_date"] = pd.to_datetime(
        data["entry_service_date"], errors="coerce", format="%d/%m/%Y"
    ).dt.strftime("%Y-%m-%d")

    data["no_show"] = data["no_show"].map({"no": 0, "yes": 1})

    data["age"] = (
        data["age"]
        .apply(
            lambda x: (
                str(x).split(".")[0]
                if isinstance(x, (int, float)) and not pd.isna(x)
                else x
            )
        )
        .replace("nan", np.nan)
    )

    display(data)

,specialty,appointment_time,gender,appointment_date,no_show,no_show_reason,disability,date_of_birth,entry_service_date,city,...,over_60_years_old,patient_needs_companion,average_temp_day,average_rain_day,max_temp_day,max_rain_day,rainy_day_before,storm_day_before,rain_intensity,heat_intensity
0,physiotherapy,13:20,M,2021-09-09,1,surto,NaN,NaN,NaN,NaN,...,0,0,20.75,0.01,23.7,0.2,1,1,no_rain,mild
1,psychotherapy,13:20,M,2021-09-09,0,NaN,NaN,NaN,NaN,NaN,...,0,0,20.75,0.01,23.7,0.2,1,1,no_rain,mild
2,speech therapy,13:20,F,2021-09-09,0,NaN,NaN,NaN,NaN,NaN,...,0,0,20.75,0.01,23.7,0.2,1,1,no_rain,mild
3,physiotherapy,13:20,F,2021-09-09,0,NaN,NaN,NaN,NaN,NaN,...,0,0,20.75,0.01,23.7,0.2,1,1,no_rain,mild
4,physiotherapy,14:00,M,2021-09-09,0,NaN,motor,10/10/1954,2020-02-05,B. CAMBORIU,...,1,1,20.75,0.01,23.7,0.2,1,1,no_rain,mild
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49588,NaN,10:20,M,2022-02-01,1,pai tem médico,intellectual,9/3/2009,2019-11-05,ITAJAÍ,...,0,0,NaN,NaN,NaN,NaN,0,0,no_rain,heavy_cold
49589,NaN,10:20,M,2022-02-01,1,NaN,NaN,NaN,NaN,NaN,...,0,0,NaN,NaN,NaN,NaN,0,0,no_rain,heavy_cold
49590,NaN,11:00,M,2022-02-01,0,NaN,intellectual,7/3/2016,2020-02-11,BOMBINHAS,...,0,1,NaN,NaN,NaN,NaN,0,0,no_rain,heavy_cold
49591,psychotherapy,11:00,M,2022-02-01,1,NaN,NaN,NaN,NaN,NaN,...,0,0,NaN,NaN,NaN,NaN,0,0,no_rain,heavy_cold
49592,NaN,11:00,M,2022-02-01,0,NaN,intellectual,25/4/2016,2020-09-02,ITAJAÍ,...,0,1,NaN,NaN,NaN,NaN,0,0,no_rain,heavy_cold

In [326]:
if not data.empty:
    if not icd10.empty:
        data = pd.merge(
            data,
            icd10.rename(columns={"definition": "icd_description"}),
            left_on="icd",
            right_on="sub-code",
            how="left",
        )

    data.drop(
        columns=[
            "average_rain_day",
            "average_temp_day",
            "max_rain_day",
            "date_of_birth",
            "sub-code",
            "storm_day_before",
        ],
        errors="ignore",
        inplace=True,
    )

    data.loc[
        data["no_show_reason"].str.contains("yes") & (data["no_show"] == 1),
        "no_show_reason",
    ] = data["no_show_reason"].str.replace("yes", "não", regex=False)

    new_cols = pd.get_dummies(
        data[["disability", "appointment_shift"]],
        columns=["disability", "appointment_shift"],
        drop_first=True,
        dtype=int,
    )
    data = pd.concat([data, new_cols], axis=1)

    data["appointment_month"] = pd.to_datetime(
        data["appointment_date"], errors="coerce"
    ).dt.month_name()

    data["is_weekend"] = (
        pd.to_datetime(data["appointment_date"], errors="coerce").dt.weekday >= 5
    )
    data["weekday"] = pd.to_datetime(
        data["appointment_date"], errors="coerce"
    ).dt.day_name()

    display(data)

,specialty,appointment_time,gender,appointment_date,no_show,no_show_reason,disability,entry_service_date,city,icd,...,max_temp_day,rainy_day_before,rain_intensity,heat_intensity,icd_description,disability_intellectual,disability_motor,appointment_shift_morning,is_weekend,weekday
0,physiotherapy,13:20,M,2021-09-09,1,surto,NaN,NaN,NaN,NaN,...,23.7,1,no_rain,mild,NaN,0,0,0,False,Thursday
1,psychotherapy,13:20,M,2021-09-09,0,NaN,NaN,NaN,NaN,NaN,...,23.7,1,no_rain,mild,NaN,0,0,0,False,Thursday
2,speech therapy,13:20,F,2021-09-09,0,NaN,NaN,NaN,NaN,NaN,...,23.7,1,no_rain,mild,NaN,0,0,0,False,Thursday
3,physiotherapy,13:20,F,2021-09-09,0,NaN,NaN,NaN,NaN,NaN,...,23.7,1,no_rain,mild,NaN,0,0,0,False,Thursday
4,physiotherapy,14:00,M,2021-09-09,0,NaN,motor,2020-02-05,B. CAMBORIU,I67,...,23.7,1,no_rain,mild,Other cerebrovascular diseases,0,1,0,False,Thursday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49588,NaN,10:20,M,2022-02-01,1,pai tem médico,intellectual,2019-11-05,ITAJAÍ,F84.5,...,NaN,0,no_rain,heavy_cold,Asperger syndrome,1,0,1,False,Tuesday
49589,NaN,10:20,M,2022-02-01,1,NaN,NaN,NaN,NaN,NaN,...,NaN,0,no_rain,heavy_cold,NaN,0,0,1,False,Tuesday
49590,NaN,11:00,M,2022-02-01,0,NaN,intellectual,2020-02-11,BOMBINHAS,F84,...,NaN,0,no_rain,heavy_cold,Pervasive developmental disorders,1,0,1,False,Tuesday
49591,psychotherapy,11:00,M,2022-02-01,1,NaN,NaN,NaN,NaN,NaN,...,NaN,0,no_rain,heavy_cold,NaN,0,0,1,False,Tuesday
49592,NaN,11:00,M,2022-02-01,0,NaN,intellectual,2020-09-02,ITAJAÍ,F84,...,NaN,0,no_rain,heavy_cold,Pervasive developmental disorders,1,0,1,False,Tuesday